# Generated by Django 5.2 on 2025-05-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
